=== kagisearch/bangs/data/bangs.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Kagi Bangs Schema",
  "description": "This schema defines the structure for bangs used by Kagi Search",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "s": {
        "type": "string",
        "title": "Website Name",
        "description": "The name of the website associated with the bang."
      },
      "d": {
        "type": "string",
        "title": "Domain",
        "description": "The domain name of the website."
      },
      "ad": {
        "type": "string",
        "title": "Alternate Domain",
        "description": "The domain of the actual website if the bang searches another website, if applicable."
      },
      "h": {
        "type": "string",
        "title": "Homepage URL",
        "description": "The URL to redirect to when the bang is invoked with no query. If not specified, defaults to the domain root."
      },
      "t": {
        "type": "string",
        "title": "Trigger",
        "description": "The specific trigger word or phrase used to invoke the bang."
      },
      "ts": {
        "type": "array",
        "title": "Additional Triggers",
        "description": "Other triggers for this bang other than the primary",
        "items": {
          "type": "string"
        }
      },
      "u": {
        "type": "string",
        "title": "Template URL",
        "description": "The URL template to use when the bang is invoked, where `{{{s}}}` is replaced by the user's query."
      },
      "x": {
        "type": "string",
        "title": "Regex pattern",
        "description": "Regex pattern that can be used for parsing the query for more complex bangs, allowing substition using `$1`, `$2`, etc."
      },
      "c": {
        "type": "string",
        "title": "Category",
        "description": "The category of the website, if applicable.",
        "enum": [
          "Entertainment",
          "Man Page",
          "Multimedia",
          "News",
          "Online Services",
          "Region search",
          "Research",
          "Shopping",
          "Tech",
          "Translation"
        ]
      },
      "sc": {
        "type": "string",
        "title": "Subcategory",
        "description": "The subcategory of the website, if applicable."
      },
      "fmt": {
        "type": "array",
        "title": "Format",
        "description": "The format flags indicating how the query should be processed.",
        "uniqueItems": true,
        "minItems": 0,
        "maxItems": 3,
        "items": {
          "type": "string",
          "enum": [
            "open_base_path",
            "url_encode_placeholder",
            "url_encode_space_to_plus"
          ]
        }
      },
      "skip_tests": {
        "type": "boolean",
        "default": false,
        "description": "Whether specs should be run on this bang"
      }
    },
    "required": [
      "d",
      "s",
      "t",
      "u"
    ],
    "additionalProperties": false
  }
}

=== kagisearch/bangs/data/assistant_bangs.json
[
  {
    "s": "Kagi Assistant",
    "d": "kagi.com",
    "t": "ai",
    "ts": [
      "as",
      "assistant",
      "research",
      "answer",
      "discuss",
      "expert",
      "llm",
      "custom",
      "asst"
    ],
    "u": "/assistant?q={{{s}}}",
    "fmt": [
      "url_encode_placeholder",
      "url_encode_space_to_plus"
    ]
  },
  {
    "s": "Kagi Assistant - Chat",
    "d": "kagi.com",
    "t": "chat",
    "u": "/assistant?q={{{s}}}&internet=off",
    "fmt": [
      "url_encode_placeholder",
      "url_encode_space_to_plus"
    ]
  },
  {
    "s": "Kagi Assistant - Code",
    "d": "kagi.com",
    "t": "code",
    "u": "/assistant?q={{{s}}}&profile=code",
    "fmt": [
      "url_encode_placeholder",
      "url_encode_space_to_plus"
    ]
  }
]
